# General
csv_file: "./files/dell_idrac.csv"
cifs_username: "annh"
cifs_password: "changeme"
cifs_share_windows_iso: 
firmware_repo_uri: '\\\\192.168.100.20\\\drm_files\\repository'
firmware_catalog_file_name: "Catalog.xml"
windows_iso_url: '//192.168.0.1/file_path/image_name.iso'
set_system_boot: "Once"
set_boot_mode: "uefi"
set_boot_target: "Cd"
system_reset_type: "graceful_restart"
# iDRAC 
validate_certs: false
target_idrac_port: 443
idrac_ntp_enable: true
targer_tz: "Asia/Saigon"
retry_count: 3
job_wait_timeout_default: 1800
batch_size: 10
# Bios
bios_clear_pending: true
bios_apply_time: "Immediate"
bios_reset_type: "graceful_restart"
bios_attributes:
  BootMode: "Uefi"
  BootSeqRetry: "Enabled"
  ProcVirtualization: "Enabled"
  ProcHyperthreading: "Enabled"
  ProcTurboMode: "Enabled"
  ProcCStates: "Disabled"
  MemFrequency: "MaxPerf"
  MemOpMode: "OptimizerMode"
  MemTest: "Disabled"
  MemoryEncryption: "Disabled"
  MemoryTraining: "MemoryTrainingFast"
  NumLock: "On"
  SysProfile: "PerfOptimized"
  EnergyPerformanceBias: "MaxPerformance"
  TimeZone: UTCP0700
  Tpm2Algorithm: "SHA256"
  Tpm2Hierarchy: "Enabled"
  TpmSecurity: "On"
  SecureBoot: "Enabled"
  #IntelTxt: "Off"
# Storage Volume
os_volume_name: "OS-RAID1"
os_vol_raid_type: "RAID 1"
data_volume_name: "DATA_RAID5"
data_vol_raid_type: "RAID 5"
raid_expected_os_disk_count: 2
raid_expected_data_disk_count: 6
os_stripe_size: 4194304 # For Windows: 4096 * 1024, Another OS: 512 * 1024
data_stripe_size: 4194304
os_disk_location: [6, 7]
data_disk_location: [0, 1, 2, 3, 4, 5]
raid_init_operation: Fast
read_cache_policy: ReadAhead
write_cache_policy: WriteThrough
disk_cache_policy: Default
