# Data files, you need input Dell information here!
csv_file: "./data_files/dell_idrac.csv"
discovered_interpreter_python: /usr/bin/python3
# Remote server contain repository
cifs_firmware_repo_uri: "\\\\192.168.25.105\\Users\\Administrator\\Downloads\\shared-folder\\drm_files\\repository"  # or use cifs_firmware_repo_uri: "\\\\192.168.0.1\\FirmwareRepo\\r740xd" or cifs_firmware_repo_uri: "//192.168.0.1/FirmwareRepo/r740xd"
firmware_catalog_file_name: Catalog.xml
cifs_share_os_iso: "//192.168.25.105/shared-folder/ubuntu-autoinstall.iso"
cifs_username: 'administrator'
cifs_password: '123qwe!@#QWE'

# General
retry_count: 3    # Retry 3 times if failed
batch_size: 5     # Runing 5 server in parallel
job_wait_timeout_default: 4500
set_system_boot: "Once"
set_boot_mode: "uefi"
set_boot_target: "Cd"
system_reset_type: "graceful_restart"

# Using proxy server if required
customer_proxy_server: 192.168.0.1   
customer_proxy_type: HTTP
customer_proxy_port: 3280
customer_proxy_uname: "proxy_user"
customer_proxy_passwd: "proxy_pwd" 

# iDRAC General configuration
validate_certs: false
target_idrac_port: 443
## NTP Configuration
idrac_ntp_enable: Enabled
ntp_server_primary: 192.168.0.1
ntp_server_secondary: 192.168.0.2
targer_tz: "Asia/Saigon" # Default CST6CDT

## iDRAC Observability
### Email Notification
smtp_server_target: 192.168.0.1
smtp_server_auth_enable: Enabled
smtp_server_port: 25
smtp_username: idrac@exaple.com
smtp_password: Changemenow

### SNMP Notification
snmp_server: 192.168.0.1
snmp_community_string: public
snmp_alert_port: 162
snmp_trap_format: SNMPv2 # Support value SNMPv1, SNMPv3
snmp_v3user: 

### Syslog Configuration
syslog_port: 514
syslog_server: 192.168.0.1
# syslog_secure_port: 6514
# SysLog.1.secureclientauth": "Anonymous"
# SysLog.1.securesyslogenable": "Disabled"

# Bios attribute configuration
bios_clear_pending: true
bios_apply_time: "Immediate"
bios_reset_type: "graceful_restart"
bios_attributes:
  # Boot mode
  BootMode: "Uefi"
  BootSeqRetry: "Enabled"
  # Enable VT
  ProcVirtualization: "Enabled"
  ProcHyperthreading: "Enabled"
  # Optimization CPU Process
  ProcTurboMode: "Enabled"
  ProcCStates: "Disabled"
  # Memory Config
  MemFrequency: "MaxPerf"
  MemOpMode: "OptimizerMode"
  MemTest: "Disabled"
  MemoryEncryption: "Disabled"
  MemoryTraining: "MemoryTrainingFast"
  NumLock: "On"
  # Bios workload profile setting 
  SysProfile: "PerfPerWattOptimizedOs"                 # Supported value: PerfOptimized, PerfPerWattOptimizedOs, PerfPerWattOptimizedDapc
  WorkloadProfile: "VtOptimizedProfile"       # Supported value: NotConfigured, HpcProfile, DbOptimizedProfile, SdsOptimizedProfile, SdsPerWattOptimizedProfile | If use another, please verify fixed values setting before apply alls
  TimeZone: UTCP0700
  # TPM, Secure boot
  Tpm2Algorithm: "SHA256"
  Tpm2Hierarchy: "Enabled"
  TpmSecurity: "On"
  SecureBoot: "Enabled"
  IntelTxt: "On"
