---
- name: Perform configuration in QNAS
  hosts: localhost
  gather_facts: no
  collections:
    - ansible.utils
    - community.general

  vars_files:
    - ./vars/qnap.yaml

  vars_prompt:
    - name: qnap_password
      prompt: "Enter QNAP admin password"
      private: true
      unsafe: true

  pre_tasks:

    - name: Read QNAS devices from CSV file
      community.general.read_csv:
        path: ./files/qnas_devices.csv
        delimiter: ','
      register: qnas_devices

  tasks:

    - name: Loop through each QNAS device
      ansible.builtin.debug:
        msg: "Processing device {{ item.serial_number }} with IP {{ item.qnap_ipaddr }}"
      loop: "{{ qnas_devices.list }}"

    - name: Perform Login to QNAP Device
      ansible.builtin.shell: |
        sshpass -p {{ qnap_password }} ssh {{ item.qnap_username }}@{{ item.qnap_ipaddr }} 'qcli -l user={{ item.qnap_username }} pw={{ qnap_password }} saveauthsid=yes'
      loop: "{{ qnas_devices.list }}"
      delegate_to: localhost

    # Setup NTP Server
    - name: Set NTP Service for QNAS NAS
      ansible.builtin.shell: |
        sshpass -p {{ qnap_password }} ssh {{ item.qnap_username }}@{{ item.qnap_ipaddr }} 'qcli_ntp -s NTPservice={{ enable_ntp }} Multicast={{ enable_ntp }} Multicast_IP={{ ntp_server }}'
      loop: "{{ qnas_devices.list }}"
      delegate_to: localhost

    # Config Timezone    
    - name: Set NTP Service for QNAS NAS
      ansible.builtin.shell: |
        sshpass -p {{ qnap_password }} ssh {{ item.qnap_username }}@{{ item.qnap_ipaddr }} 'qcli_timezone --settime timezone=47 timeformat=24 dateformat=8'
      loop: "{{ qnas_devices.list }}"
      delegate_to: localhost

    # Create 2 SSD Disk Cache
    - name: Create Disk Cache
      ansible.builtin.shell: |
        sshpass -p {{ qnap_password }} ssh {{ item.qnap_username }}@{{ item.qnap_ipaddr }} 'qcli_cache --createssdcachevolume cache_type="{{ disk_cache_type }}" raidLevel="{{ disk_cache_raid }}" cache_mode="{{ disk_cache_mode }}" diskID="{{ disk_cache_id }}"'
      loop: "{{ qnas_devices.list }}"
      delegate_to: localhost

    # Create Storage Pool and ISCSI LUN 
    - name: Create Storage Pool
      ansible.builtin.shell: |
        sshpass -p {{ qnap_password }} ssh {{ item.qnap_username }}@{{ item.qnap_ipaddr }} 'qcli_pool --createpool diskID="{{ pool_disk_id }}" raidLevel="{{ pool_raid }}" Stripe="{{ pool_stripe }}" sed_pool_encrypt="{{ pool_sed_encrypt }}" sed_pool_save_key="{{ pool_sed_save_key }}" sed_pool_key_str="{{ pool_sed_keystring }}" pool_tiering="{{ pool_auto_tier }}"' 
      loop: "{{ qnas_devices.list }}"
      delegate_to: localhost

    - name: Detect Storage Pool ID
      ansible.builtin.shell: |
        sshpass -p {{ qnap_password }} ssh {{ item.qnap_username }}@{{ item.qnap_ipaddr }} 'qcli_pool --poollist' 
      loop: "{{ qnas_devices.list }}"
      delegate_to: localhost
      register: pool_id

    - name: Set detect_pool_id
      set_fact:
        detect_pool_id: "{{ pool_id.results[0].stdout_lines[3] | trim }}"

    - debug:
        var: detect_pool_id

    - name: Create ISCSI Target
      ansible.builtin.shell: |
        sshpass -p {{ qnap_password }} ssh {{ item.qnap_username }}@{{ item.qnap_ipaddr }} 'qcli_iscsi --createtarget Name={{ item.iscsi_profile_name }} Alias={{ item.iscsi_alias_name }}'
      loop: "{{ qnas_devices.list }}"
      delegate_to: localhost

    - name: Detect Target ISCSI ID
      ansible.builtin.shell: |
        sshpass -p {{ qnap_password }} ssh {{ item.qnap_username }}@{{ item.qnap_ipaddr }} 'qcli_iscsi --targetlist' 
      loop: "{{ qnas_devices.list }}"
      delegate_to: localhost
      register: iscsi_target

    - name: Extract iscsi_target_id
      set_fact:
        iscsi_target_id: "{{ iscsi_target.results[0].stdout | regex_search('targetID\\s+(\\d+)', '\\1') }}"

    - debug:
        var: iscsi_target_id

    - name: Create ISCSI LUN for Quorum
      ansible.builtin.shell: |
        sshpass -p {{ qnap_password }} ssh {{ item.qnap_username }}@{{ item.qnap_ipaddr }} 'qcli_iscsi --createlun Name={{ block_quorum_lun_name }} Allocation={{ block_quorum_allocation }} Capacity={{ block_quorum_lun_capacity }} SectorSize={{ block_quorum_lun_sector }} LUNType=Block volumeID="{{ block_quorum_lun_id }}" Threshold=80 SSDCache="{{ block_quorum_cache }}" poolID={{ detect_pool_id }}'
      loop: "{{ qnas_devices.list }}"
      delegate_to: localhost

    - name: Create ISCSI LUN for Data
      ansible.builtin.shell: |
        sshpass -p {{ qnap_password }} ssh {{ item.qnap_username }}@{{ item.qnap_ipaddr }} 'qcli_iscsi --createlun Name={{ block_data_lun_name }} Allocation={{ block_data_allocation }} Capacity={{ block_data_lun_capacity }} SectorSize={{ block_data_lun_sector }} LUNType=Block volumeID="{{ block_data_lun_id }}" Threshold=80 SSDCache="{{ block_data_cache }}" poolID={{ detect_pool_id }}'
      loop: "{{ qnas_devices.list }}"
      delegate_to: localhost

    - name: Mapping ISCSI Target & iSCSI Quorum LUN 
      ansible.builtin.shell: |
        sshpass -p {{ qnap_password }} ssh {{ item.qnap_username }}@{{ item.qnap_ipaddr }} 'qcli_iscsi --iscsimap lunID=0 targetID="{{ iscsi_target_id }}"'
      loop: "{{ qnas_devices.list }}"
      delegate_to: localhost

    - name: Mapping ISCSI Target & iSCSI Data LUN
      ansible.builtin.shell: |
        sshpass -p {{ qnap_password }} ssh {{ item.qnap_username }}@{{ item.qnap_ipaddr }} 'qcli_iscsi --iscsimap lunID=1 targetID="{{ iscsi_target_id }}"'
      loop: "{{ qnas_devices.list }}"
      delegate_to: localhost

    # Upload firmware update file to local machine
    - name: Copy update file to remote machine {{ item.serial_number }} with IP {{ item.qnap_ipaddr }}
      ansible.builtin.copy:
        src: ./files/{{ update_fw_name }}
        dest: /tmp/{{ update_fw_name }}
        owner: admin
        group: administrators
        mode: '0644'    
      loop: "{{ qnas_devices.list }}"

    #  Upgrade firmware 
    - name: Copy update file to remote machine {{ item.serial_number }} with IP {{ item.qnap_ipaddr }}
      ansible.builtin.shell: |
        sshpass -p {{ qnap_password }} ssh {{ item.qnap_username }}@{{ item.qnap_ipaddr }} 'qcli_firmwareupdate --updatefirmware uploadfilename=/tmp/{{ update_fw_name }} reboot=1'
      loop: "{{ qnas_devices.list }}"
      delegate_to: localhost