# =======================================================================================================
# PHASE 1: INITIALIZNG DELL POWEREDGE SEREVER VIA IDRAC MODULE - IDRAC/ BIOS /UPGRADE FW /ONCE BOOT CDROM 
# =======================================================================================================
- name: Standardized Dell PowerEdge deployment
  hosts: idrac_servers
  connection: local
  gather_facts: false
  vars_files:
    - ./vars/vars.yaml
  serial: "{{ batch_size | default(5) }}"
  collections:
    - dellemc.openmanage
    - ansible.utils
    - ansible.windows
    - community.general

  vars:
    enable_ntp_config: "{{ hostvars['localhost']['enable_ntp_config'] }}"
    enable_snmp_notification: "{{ hostvars['localhost']['enable_snmp_notification'] }}"
    enable_syslog_notification: "{{ hostvars['localhost']['enable_syslog_notification'] }}"
    enable_email_notification: "{{ hostvars['localhost']['enable_email_notification'] }}"

  tasks:
    - name: Announce target server perform reconfig
      ansible.builtin.debug:
        msg: 'Perform configure on Dell Device with Service Tag {{ inventory_hostname }} - Temporarily IP Adrress {{ server.dhcp_ip }} - Permanent IP Adrress {{ server.static_ip }}'

    # - name: Test batch process
    #   ansible.builtin.include_role:
    #     name: show_status

    # - name: Configure iDRAC 
    #   ansible.builtin.include_role:
    #     name: idrac_config

    # - name: Configure BIOS
    #   ansible.builtin.include_role:
    #     name: bios_config

    # - name: Perform Create RAID on Storage Controller
    #   ansible.builtin.include_role:
    #     name: reconfig_raid

    # - name: Upgrade firmware when repository is provided
    #   ansible.builtin.include_role:
    #     name: upgrade_firmware
    #   when: cifs_firmware_repo_uri is defined

    - name: Deploy operating system when ISO is provided
      ansible.builtin.include_role:
        name: os_deployment
      when: cifs_share_os_iso is defined 

