---
- name: Clear pending BIOS attributes
  dellemc.openmanage.idrac_bios:
    idrac_ip: "{{ server.permanent_ip }}"
    idrac_user: "{{ server.username }}"
    idrac_port: "{{ target_idrac_port }}"
    idrac_password: "{{ idrac_root_passwd }}"
    validate_certs: "{{ validate_certs }}"
    clear_pending: true
  tags: bios_clear_pending
  when: bios_clear_pending | bool

- name: Perform a power cycle on the device
  dellemc.openmanage.redfish_powerstate:
    baseuri: "{{ server.permanent_ip }}:{{ target_idrac_port }}"
    username: "{{ server.username }}"
    password: "{{ idrac_root_passwd }}"
    validate_certs: "{{ validate_certs }}"
    reset_type: "PowerCycle"

- name: Apply BIOS baseline
  dellemc.openmanage.idrac_bios:
    idrac_ip: "{{ server.permanent_ip }}"
    idrac_user: "{{ server.username }}"
    idrac_port: "{{ target_idrac_port }}"
    idrac_password: "{{ idrac_root_passwd }}"
    validate_certs: "{{ validate_certs }}"
    apply_time: "{{ bios_apply_time }}"
    reset_type: "{{ bios_reset_type }}"
    job_wait: true
    job_wait_timeout: "{{ bios_job_wait_timeout | default(1200) }}"
    attributes: "{{ bios_attributes }}"
  register: bios_apply

- name: Pause for 5 minutes before running next step
  ansible.builtin.pause:
    minutes: 5