- name: dell server configuration
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  collections:
    - dellemc.openmanage
  vars_files:
    - ./vars/server-vars.yaml
  pre_tasks:
  - name: Reading CSV file for retriving Vmware information
    read_csv:
      delimiter: ','
      path: ./vars/server-info.csv
    register: server_info
  tasks:
  - name: Change root password
    dellemc.openmanage.idrac_user:
      idrac_ip: "{{ server.IDRAC_IP }}"
      idrac_user: "root"
      idrac_password: "{{ server.IDRAC_PW }}"
      state: present
      user_name: "{{ new_account }}"
      user_password: "{{ administrator_password }}"
      validate_certs: false
    loop: "{{ server_info.list }}"
    loop_control:
      loop_var: server
