### Reference variables in
# idrac_attributes: https://192.168.25.50/redfish/v1/Managers/iDRAC.Embedded.1/Oem/Dell/DellAttributes/iDRAC.Embedded.1
# lifecycle_controller_attributes: https://192.168.25.50/redfish/v1/Managers/iDRAC.Embedded.1/Oem/Dell/DellAttributes/LifecycleController.Embedded.1
# system_attributes: https://192.168.25.50/redfish/v1/Managers/iDRAC.Embedded.1/Oem/Dell/DellAttributes/System.Embedded.1
### ============================================ General Configuration ============================================ ###
idrac_wait_timeout: 600
### ============================================ iDRAC Configuration ============================================ ###
idrac_attr:
  NIC.1.Enable: "Enabled"
  IPv4.1.Enable: "Enabled"
  IPv6.1.Enable: "Disabled"
  IPv4.1.DHCPEnable: "Disabled"
  IPv4.1.Address: "{{ server.permanent_ip }}"
  IPv4.1.Netmask: "{{ server.netmask }}"
  IPv4.1.Gateway: "{{ server.gateway }}"
  IPv4.1.DNS1: "{{ server.preferred_dns }}"
  NIC.1.DNSDomainName: ""
  NIC.1.DNSRacName: "{{ server.dns_idrac_name }}"
  Time.1.Timezone: "{{ target_timezone }}"
lifecycle_controller_attr:
  LCAttributes.1.AutoUpdate: "Disabled"
  LCAttributes.1.CollectSystemInventoryOnRestart: "Enabled"
system_attr:
  ServerPwr.1.PSRedPolicy: "A/B Grid Redundant"
  ServerPwr.1.PowerCapSetting: "Disabled"
  ServerPwr.1.PSRapidOn: "Disabled"
  ServerPwr.1.GridACurrentCapSetting: "Disabled"
  ServerPwr.1.GridBCurrentCapSetting: "Disabled"
  ThermalSettings.1.ThermalProfile: "Default Thermal Profile Settings"
### ============================================ NTP Notification ============================================ ###
idrac_ntp_enable: "Enabled"
ntp_server_primary: ""
ntp_server_secondary: ""
target_timezone: "Asia/Saigon"                                          # Default CST6CDT
### ============================================ Email Notification ============================================ ###
smtp_server_target: ""
smtp_server_auth_enable: "Enabled"
smtp_server_port: ""
smtp_username: ""
smtp_password: ""
### ============================================ SMNP Notification ============================================ ###
snmp_server: ""
snmp_community_string: "public"
snmp_alert_port: ""
snmp_trap_format: "SNMPv2"                                              # Support value SNMPv1, SNMPv3
snmp_v3user: 
### ============================================ Syslog Notification ============================================ ###
syslog_port: ""
syslog_server: ""
# syslog_secure_port: 6514
# SysLog.1.secureclientauth": "Anonymous"
# SysLog.1.securesyslogenable": "Disabled"