#### Reference variables in
# idrac_attributes: https://192.168.25.50/redfish/v1/Managers/iDRAC.Embedded.1/Oem/Dell/DellAttributes/iDRAC.Embedded.1
# lifecycle_controller_attributes: https://192.168.25.50/redfish/v1/Managers/iDRAC.Embedded.1/Oem/Dell/DellAttributes/LifecycleController.Embedded.1
# system_attributes: https://192.168.25.50/redfish/v1/Managers/iDRAC.Embedded.1/Oem/Dell/DellAttributes/System.Embedded.1
####
# - name: Change iDRAC root password when default password is provided
#   dellemc.openmanage.idrac_user:
#     idrac_ip: "{{ server.temporary_ip }}"
#     idrac_user: "{{ server.username }}"
#     idrac_password: "{{ server.def_passwd }}"
#     idrac_port: "{{ target_idrac_port }}"
#     validate_certs: "{{ validate_certs }}"
#     user_name: "{{ server.username }}"
#     user_password: "{{ idrac_root_passwd }}"
#   register: idrac_password_changed
#   no_log: true

- name: Configure iDRAC, Power Policy and Lifecycle Controller attributes 
  dellemc.openmanage.idrac_attributes:
    idrac_ip: "{{ server.temporary_ip }}"
    idrac_user: "{{ server.username }}"
    idrac_port: "{{ target_idrac_port }}"
    idrac_password: "{{ idrac_root_passwd }}"
    validate_certs: "{{ validate_certs }}"
    idrac_attributes: "{{ idrac_attr }}" 
    system_attributes: "{{ system_attr }}"
    lifecycle_controller_attributes: "{{ lifecycle_controller_attr }}"
  register: idrac_custom_attr_changed

- name: Wait for iDRAC HTTPS after static IP change
  ansible.builtin.wait_for:
    host: "{{ server.permanent_ip }}"
    port: 443
    timeout: "{{ idrac_wait_timeout | default(360) }}"
  register: waiting_idrac_up

- name: Configure NTP service for iDRAC
  dellemc.openmanage.idrac_attributes:
    idrac_ip: "{{ server.permanent_ip }}"
    idrac_user: "{{ server.username }}"
    idrac_port: "{{ target_idrac_port }}"
    idrac_password: "{{ idrac_root_passwd }}"
    validate_certs: "{{ validate_certs }}"
    idrac_attributes:
      NTPConfigGroup.1.NTPEnable: "{{ idrac_ntp_enable }}"
      NTPConfigGroup.1.NTP1: "{{ ntp_server_primary }}"
      NTPConfigGroup.1.NTP2: "{{ ntp_server_secondary | default('') }}"
  register: idrac_ntp_register
  when:
    - enable_ntp_config | lower in ['y', 'yes']
    - ntp_server_primary is define
    - idrac_ntp_enable is define

- name: Configure the iDRAC attributes for SNMP alert settings.
  dellemc.openmanage.idrac_attributes:
    idrac_ip: "{{ server.permanent_ip }}"
    idrac_user: "{{ server.username }}"
    idrac_port: "{{ target_idrac_port }}"
    idrac_password: "{{ idrac_root_passwd }}"
    validate_certs: "{{ validate_certs }}"
    idrac_attributes:
      SNMP.1.AgentEnable: "Enabled"
      SNMP.1.SNMPProtocol: All
      SNMP.1.TrapFormat: "{{ snmp_trap_format }}"
      SNMP.1.AgentCommunity: "{{ snmp_community_string }}"
      SNMP.1.AlertPort: "{{ snmp_alert_port }}"
      SNMPAlert.1.State: Enabled
      SNMPAlert.1.Destination: "{{ snmp_server }}"
  register: idrac_snmp_register
  when:
    - enable_snmp_notification | lower in ['y', 'yes']
    - snmp_server is define
    - snmp_community_string is define
    - snmp_alert_port is define
    - snmp_trap_format is define

- name: Configure the iDRAC attributes for SMTP alert settings.
  dellemc.openmanage.idrac_attributes:
    idrac_ip: "{{ server.permanent_ip }}"
    idrac_user: "{{ server.username }}"
    idrac_port: "{{ target_idrac_port }}"
    idrac_password: "{{ idrac_root_passwd }}"
    validate_certs: "{{ validate_certs }}"
    idrac_attributes:
      RemoteHosts.1.SMTPServerIPAddress: "{{ smtp_server_target }}"
      RemoteHosts.1.SMTPAuthentication: "{{ smtp_server_auth_enable }}"
      RemoteHosts.1.SMTPPort: "{{ smtp_server_port }}"
      RemoteHosts.1.SMTPUserName: "{{ smtp_username }}"
      RemoteHosts.1.SMTPPassword: "{{ smtp_password }}"
  register: idrac_smtp_register
  when:
    - enable_email_notification | lower in ['y', 'yes']
    - smtp_server_target is define
    - smtp_server_auth_enable is define
    - smtp_server_port is define
    - smtp_username is define
    - smtp_password is define

- name: Configure the iDRAC attributes for Syslog settings
  dellemc.openmanage.idrac_attributes:
    idrac_ip: "{{ server.permanent_ip }}"
    idrac_user: "{{ server.username }}"
    idrac_port: "{{ target_idrac_port }}"
    idrac_password: "{{ idrac_root_passwd }}"
    validate_certs: "{{ validate_certs }}"
    idrac_attributes:
      SysLog.1.SysLogEnable: Enabled
      SysLog.1.Server1: "{{ syslog_server }}"
      SysLog.1.Port: "{{ syslog_port }}"
      SysLog.1.securesyslogenable: Disabled
  register: idrac_syslog_register
  when: 
    - enable_syslog_notification | lower in ['y', 'yes']
    - syslog_port is define
    - syslog_server is define