# General settings
csv_file: ./data_files/hpe_ilo.csv
batch_size: 7                                              # How many parallel remediate config on HPE Server
retries_count: 10                                          # How many retry before it's complete failed
polling_interval: 60                                       # Time interval between retry count 
ilo_validate_certs: false
ilo_port: 443