retries_count: 15
polling_interval: 6
reboot_uri: "/redfish/v1/Systems/System.Embedded.1/Actions/ComputerSystem.Reset"
perc_firmware: "/mnt/c/Users/annh/Downloads/SAS-RAID_Firmware_8020K_WN64_52.30.0-6115_A10.EXE"
idrac_firmware: "/mnt/c/Users/annh/Downloads/iDRAC-with-Lifecycle-Controller_Firmware_KYWDC_WN64_7.20.80.50_A00.EXE"
bios_firmware: "/mnt/c/Users/annh/Downloads/BIOS_0HH4V_WN64_2.9.5.EXE"