---
- name: Fail if OS install requested but no filename provided
  ansible.builtin.fail:
    msg: "Review vars/main.yaml And Provide All Information Required"
  when:
    - not local_http_url
    - not os_iso_file_name

- name: Create Redfish credentials access token
  community.general.redfish_command:
    category: Sessions
    command: CreateSession
    baseuri: "{{ hpe_server.permanent_ipv4 }}"
    username: "{{ hpe_server.ilo_user_default | default('Administrator') }}"
    password: "{{ new_ilo_admin_password }}"
  register: redfish_login_token

- name: Set Fact for Redfish credentials access token
  ansible.builtin.set_fact:
    ilo_x_auth_token: "{{ redfish_login_token.session.token }}"
    ilo_x_uri: "{{ redfish_login_token.session.uri }}"

- name: Verify Redfish session token exists
  ansible.builtin.assert:
    that:
      - ilo_x_auth_token is defined
      - ilo_x_auth_token | length > 0
    fail_msg: "Redfish authentication token is missing."

- name: Mount Service Pack for ProLiant ISO to Virtual Media
  ansible.builtin.uri:
    url: "https://{{ hpe_server.permanent_ipv4 }}/redfish/v1/Managers/1/VirtualMedia/2/Actions/Oem/Hpe/HpeiLOVirtualMedia.InsertVirtualMedia"
    validate_certs: "{{ ilo_validate_certs | default(false) | bool }}"
    method: POST
    status_code: [200, 201, 202]
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ ilo_x_auth_token }}"
    body_format: json
    body:
      Image: "{{ install_os_iso_path }}"
    when:
      - install_os_iso_path.endswith('.iso')
      - local_http_url is defined
      - os_iso_file_name is defined
  register: insert_virtual_media_os

- name: Making sure next boot will be on mounted ISO
  ansible.builtin.uri:
    url: "https://{{ hpe_server.permanent_ipv4 }}/redfish/v1/Managers/1/VirtualMedia/2/" 
    method: PATCH
    status_code: [200, 202]
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ ilo_x_auth_token }}"
    body_format: json
    body:
      Oem:
        Hpe:
          BootOnNextServerReset: true
  when:
    - insert_virtual_media_os.status in [200, 201, 202]
  register: next_boot_os

- name: Reboot server for booting into mounted ISO
  ansible.builtin.uri:
    url:  "https://{{ hpe_server.permanent_ipv4 }}/redfish/v1/Systems/1/Actions/ComputerSystem.Reset/" 
    validate_certs: "{{ ilo_validate_certs | default(false) | bool }}"
    method: "POST"
    status_code: [200, 202]
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ ilo_x_auth_token }}"
    body_format: json
    body:
      ResetType: "GracefulRestart"
  when: 
    - insert_virtual_media_os.status in [200, 201, 202] or next_boot_os in [200, 202]