# Document reference: https://servermanagementportal.ext.hpe.com/docs
--- 
- name:  "Phase 2: Initializting HPE ProLiant Server via Ansible Module"
  hosts: hpe-server-group
  connection: local
  gather_facts: false
  vars_files:
    - ./vars/vars_file.yaml
  collections:
    - community.general
    - hpe.ilo

  serial: "{{ batch_size | default(7) }}"

  vars:
    enable_ntp_config: "{{ hostvars['localhost']['enable_ntp_config'] }}"
    enable_snmp_notification: "{{ hostvars['localhost']['enable_snmp_notification'] }}"
    enable_syslog_notification: "{{ hostvars['localhost']['enable_syslog_notification'] }}"
    enable_email_notification: "{{ hostvars['localhost']['enable_email_notification'] }}"
    new_ilo_admin_password: "{{ hostvars['localhost']['new_ilo_admin_password'] }}"

  pre_tasks:
    - name: Configure HPE Server
      ansible.builtin.debug:
        msg: 'Including Serial number: {{ inventory_hostname }} has DHCP IP: {{ hpe_server.dhcp_ipv4 }} and replace with new IPv4 {{ hpe_server.permanent_ipv4 }}'

  tasks:

    # - name: Perform update iLO Attributes
    #   ansible.builtin.include_role:
    #     name: ilo_attributes_config

    # - name: Perform update BIOS Attributes
    #   ansible.builtin.include_role:
    #     name: bios_attributes_config

    - name: Create logical drives if do not existed 
      ansible.builtin.include_role:
        name: create_os_volume

    # - name: Upgrade device firmware with single file
    #   ansible.builtin.include_role:
    #     name: firmware_update