# Document reference: https://servermanagementportal.ext.hpe.com/docs
--- 
- name:  "Phase 2: Initializting HPE ProLiant Server via Ansible Module"
  hosts: hpe-server-group
  connection: local
  gather_facts: false
  vars_files:
    - ./vars/vars_file.yaml
  collections:
    - community.general
    - hpe.ilo

  serial: "{{ batch_size | default(7) }}"

  vars:
    enable_ntp_config: "{{ hostvars['localhost']['enable_ntp_config'] }}"
    enable_snmp_notification: "{{ hostvars['localhost']['enable_snmp_notification'] }}"
    enable_syslog_notification: "{{ hostvars['localhost']['enable_syslog_notification'] }}"
    enable_email_notification: "{{ hostvars['localhost']['enable_email_notification'] }}"
    new_ilo_admin_password: "{{ hostvars['localhost']['new_ilo_admin_password'] }}"

  pre_tasks:
    - name: Configure HPE Server
      ansible.builtin.debug:
        msg: 'Including Serial number: {{ inventory_hostname }} has DHCP IP: {{ hpe_server.dhcp_ipv4 }} and replace with new IPv4 {{ hpe_server.permanent_ipv4 }}'

  tasks:

    - name: Perform Update iLO Attributes
      ansible.builtin.include_role:
        name: ilo_attributes_config

    - name: Perform Update BIOS Attributes
      ansible.builtin.include_role:
        name: bios_attributes_config

    - name: Create Logical Drives If Current Volume Do Not Existed 
      ansible.builtin.include_role:
        name: create_os_volume

    # BIOS > iLO > Service Pack for ProLiant, all action perform in Virtual Media
    # If USB SPP ISO plug into Server, please comment this task then perform
    # Uncomment reboot task because next action will reboot server and automatically booting into CDROM while OS not install yet
    - name: Upgrade Server Firmware
      ansible.builtin.include_role:
        name: firmware_update

    # Only uncomment when plug Service Pack for Proliant USB direct to Server
    # - name: Upgrade Service Pack for Proliant via USB
    #   ansible.builtin.uri:
    #     url:  "https://{{ hpe_server.permanent_ipv4 }}/redfish/v1/Systems/1/Actions/ComputerSystem.Reset/" 
    #     user: "{{ hpe_server.ilo_user_default | default('Administrator') }}"
    #     password: "{{ new_ilo_admin_password }}"
    #     validate_certs: "{{ ilo_validate_certs | default(false) | bool }}"
    #     force_basic_auth: true
    #     method: "POST"
    #     status_code: [200, 202]
    #     headers:
    #       Content-Type: "application/json"
    #     body_format: json
    #     body:
    #       ResetType: "GracefulRestart"

    - name: Mounted Operating System ISO into Devices
      ansible.builtin.include_role:
        name: install_os_virtual_media

    - ansible.builtin.debug:
        msg: "ALL TASKS HAVE BEEN EXECUTED, PLEASE ACCESS ILO WEBUI TO MONITOR AND PERFORM CONFIGURATION"
