# =======================================================================================================
# PHASE 1: INITIALIZNG DELL POWEREDGE SEREVER VIA IDRAC MODULE - IDRAC/ BIOS /UPGRADE FW /ONCE BOOT CDROM 
# =======================================================================================================
- name: Standardized Dell PowerEdge deployment
  hosts: idrac_servers
  connection: local
  gather_facts: false
  vars_files:
    - ./vars/vars.yaml
  serial: "{{ batch_size | default(5) }}"
  collections:
    - dellemc.openmanage
    - ansible.utils
    - ansible.windows
    - community.general

  vars:
    enable_ntp_config: "{{ hostvars['localhost']['enable_ntp_config'] }}"
    enable_snmp_notification: "{{ hostvars['localhost']['enable_snmp_notification'] }}"
    enable_syslog_notification: "{{ hostvars['localhost']['enable_syslog_notification'] }}"
    enable_email_notification: "{{ hostvars['localhost']['enable_email_notification'] }}"
    idrac_root_passwd: "{{ hostvars['localhost']['idrac_root_passwd'] }}"

  tasks:
    - name: Announce target server perform reconfig
      ansible.builtin.debug:
        msg: 'Configure on Dell Server with Service Tag {{ inventory_hostname }} - Temporary IP Adrress {{ server.temporary_ip }} - Permanent IP Adrress {{ server.permanent_ip }}'

    # - name: Test batch process
    #   ansible.builtin.include_role:
    #     name: show_status

    # - name: Perform customize iDRAC Attributes
    #   ansible.builtin.include_role:
    #     name: idrac_configuration

    # - name: Perform customize BIOS Attributes
    #   ansible.builtin.include_role:
    #     name: bios_configuration

    # - name: Perform Create RAID on Storage Controller
    #   ansible.builtin.include_role:
    #     name: idrac_raid_configure

    - name: Upgrade firmware when repository is provided
      ansible.builtin.include_role:
        name: idrac_fw_upgrade
      when: cifs_firmware_repo_uri is defined

    # - name: Deploy operating system when ISO is provided
    #   ansible.builtin.include_role:
    #     name: idrac_os_deploy
    #   when: cifs_operating_system_iso_url is defined