---
- name: Perform Power ON server for loading hardware
  community.general.redfish_command:
    category: Systems
    command: PowerOn
    baseuri: "{{ hpe_server.dhcp_ipv4 }}"
    username: "{{ hpe_server.ilo_user_default | default('Administrator') }}"
    password: "{{ hpe_server.ilo_passwd_default }}"

- name: Waiting until device booting complete
  ansible.builtin.uri:
    url: "https://{{ hpe_server.dhcp_ipv4 }}/redfish/v1/Systems/1"
    user: "{{ hpe_server.ilo_user_default | default('Administrator') }}"
    password: "{{ hpe_server.ilo_passwd_default }}"
    validate_certs: "{{ ilo_validate_certs | default(false) | bool }}"
    method: "GET"
    status_code: [200, 202]
    force_basic_auth: yes
    return_content: yes
    headers:
      Content-Type: "application/json"
  register: poweron_job_result        # Noted: Status after server booting iLO6: FinishedPost, iLO5: InPostDiscoveryComplete
  until: 
    - poweron_job_result.json.PowerState == 'On'
    - (poweron_job_result.json.Oem['Hpe'].PostState == 'FinishedPost') or (poweron_job_result.json.Oem['Hpe'].PostState == 'InPostDiscoveryComplete')
    - poweron_job_result.json.Oem['Hpe'].DeviceDiscoveryComplete.DeviceDiscovery == 'vMainDeviceDiscoveryComplete'
  retries: 10
  delay: 30

- name: Checking device health.... 
  ansible.builtin.uri:
    url: "https://{{ hpe_server.dhcp_ipv4 }}/redfish/v1/Systems/1"
    user: "{{ hpe_server.ilo_user_default | default('Administrator') }}"
    password: "{{ hpe_server.ilo_passwd_default }}"
    validate_certs: "{{ ilo_validate_certs | default(false) | bool }}"
    method: "GET"
    use_proxy: yes
    status_code: [200, 202]
    return_content: yes
    force_basic_auth: yes
    headers:
      Content-Type: "application/json"
  register: server_status

- name: Getting device health status....
  ansible.builtin.set_fact:
    server_health: "{{ server_status.json.Status.Health }}"
    server_health_rollup: "{{ server_status.json.Status.HealthRollup }}"
    server_state: "{{ server_status.json.Status.State }}"

- name: Pause Playbook if any server health is NOT 'OK'
  ansible.builtin.pause:
    prompt: |
      [WARNING] One or more servers are reporting a health status other than 'OK'!
      Please check the physical or iLO status of the servers before proceeding.
      - Press ENTER to ignore and continue running the Playbook.
      - Press Ctrl+C and then 'A' to ABORT the entire process.        
  run_once: true
  when:
  - ansible_play_hosts | map('extract', hostvars, 'server_health') | reject('equalto', 'OK') | list | length > 0
  - ansible_play_hosts | map('extract', hostvars, 'server_health_rollup') | reject('equalto', 'OK') | list | length > 0
  - ansible_play_hosts | map('extract', hostvars, 'server_state') | reject('equalto', 'Enabled') | list | length > 0

- name: Change iLO dedicated network to permanent IPv4 address
  ansible.builtin.uri:
    url: "https://{{ hpe_server.dhcp_ipv4 }}/redfish/v1/Managers/1/EthernetInterfaces/1/"
    user: "{{ hpe_server.ilo_user_default | default('Administrator') }}"
    password: "{{ hpe_server.ilo_passwd_default }}"
    validate_certs: "{{ ilo_validate_certs | default(false) | bool }}"
    method: "PATCH"
    status_code: [200, 202]
    force_basic_auth: yes
    return_content: yes
    headers:
      Content-Type: "application/json"
    body_format: json
    body:
      InterfaceEnabled: true
      VLAN:
        VLANEnable: false
        VLANId: null
      IPv4StaticAddresses:
        - Address: "{{ hpe_server.permanent_ipv4 }}"
          SubnetMask: "{{ hpe_server.subnet_mask }}"
          Gateway: "{{ hpe_server.ipv4_gateway }}"
      StaticNameServers:
        - "{{ hpe_server.preferred_dns }}"
      HostName: "{{ hpe_server.ilo_hostname }}"
  register: ilo_ipaddr_updated

# - name: Restart iLO gracefully to take affect
#   community.general.redfish_command:
#     category: Manager
#     command: GracefulRestart
#     # resource_id: "1"
#     baseuri: "{{ hpe_server.dhcp_ipv4 }}"
#     username: "{{ hpe_server.ilo_user_default | default('Administrator') }}"
#     password: "{{ hpe_server.ilo_passwd_default }}"

- name: Wait for iLO Reboot Completion and Port "{{ ilo_port }}" available
  ansible.builtin.wait_for:
    host: "{{ hpe_server.permanent_ipv4 }}"
    port: "{{ ilo_port }}"
    delay: 30
    timeout: 300

- name: Change iLO Administrator password     # Doc ref: https://servermanagementportal.ext.hpe.com/docs/references_and_material/blogposts/etc/changefactorypasswd/changefactorypasswd
  ansible.builtin.uri:
    url: "https://{{ hpe_server.permanent_ipv4 }}/redfish/v1/AccountService/Accounts/1/"
    user: "{{ hpe_server.ilo_user_default | default('Administrator') }}"
    password: "{{ hpe_server.ilo_passwd_default }}"
    validate_certs: "{{ ilo_validate_certs | default(false) | bool }}"
    method: "PATCH"
    status_code: [200, 202]
    force_basic_auth: yes
    return_content: yes
    headers:
      Content-Type: "application/json"
    body_format: json
    body:
      Password: "{{ new_ilo_admin_password }}"
  register: ilo_passwd_updated

- name: Create Redfish credentials access token
  community.general.redfish_command:
    category: Sessions
    command: CreateSession
    baseuri: "{{ hpe_server.permanent_ipv4 }}"
    username: "{{ hpe_server.ilo_user_default | default('Administrator') }}"
    password: "{{ new_ilo_admin_password }}"
  register: redfish_login_token

- name: Set Fact for Redfish credentials access token
  ansible.builtin.set_fact:
    ilo_x_auth_token: "{{ redfish_login_token.session.token }}"
    ilo_x_uri: "{{ redfish_login_token.session.uri }}"

- name: Verify Redfish session token exists
  ansible.builtin.assert:
    that:
      - ilo_x_auth_token is defined
      - ilo_x_auth_token | length > 0
    fail_msg: "Redfish authentication token is missing."

- name: Configure Timezone for iLO 
  ansible.builtin.uri:
    url: "https://{{ hpe_server.permanent_ipv4 }}/redfish/v1/Managers/1/DateTime/"
    validate_certs: "{{ ilo_validate_certs | default(false) | bool }}"
    method: "PATCH"
    status_code: [200, 202]
    return_content: yes
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ ilo_x_auth_token }}"
    body_format: json
    body:
      TimeZone:
        Index: 28
        Name: "Bangkok, Hanio, Jakarta, Novosibirsk, Astana, Krasnoyarsk"

- name: Update Server Name and Host FQDN/IP via Redfish REST API
  ansible.builtin.uri:
    url: "https://{{ hpe_server.permanent_ipv4 }}/redfish/v1/Systems/1/"
    validate_certs: false
    method: PATCH
    status_code: [200, 204]
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ ilo_x_auth_token }}"
    body_format: json
    body:
      HostName: "{{ hpe_server.ilo_hostname }}"
      Oem:
        Hpe:
          ServerFQDN: "{{ hpe_server.ilo_hostname }}.{{hpe_server.dns_domain_name}}"
  register: ilo_change_hostname

- name: Set NTP Servers
  community.general.ilo_redfish_config:
    category: Manager
    command: SetNTPServers
    baseuri:  "{{ hpe_server.permanent_ipv4 }}"      
    auth_token: "{{ ilo_x_auth_token }}"
    attribute_name: StaticNTPServers
    attribute_value: "{{ ntp_server_ipaddr | default('time.windows.com') }}"
  when: enable_ntp_config | lower in ['y', 'yes']

- name: Delete Redfish session
  community.general.redfish_command:
    category: Sessions
    command: DeleteSession
    baseuri: "{{ hpe_server.permanent_ipv4 }}"
    session_uri: "{{ ilo_x_uri }}"
    auth_token: "{{ ilo_x_auth_token }}"
  when:
    - ilo_x_uri is defined
    - ilo_x_auth_token is defined