- name: Show status of the Lifecycle Controller"
  dellemc.openmanage.idrac_lifecycle_controller_status_info:
    idrac_ip: "{{ server.static_ip }}"
    idrac_user: "{{ server.username }}"
    idrac_port: "{{ target_idrac_port }}"
    idrac_password: "{{ server.temp_passwd }}"
    validate_certs: "{{ validate_certs }}"

- name: Get System Inventory"
  dellemc.openmanage.idrac_system_info:
    idrac_ip: "{{ server.static_ip }}"
    idrac_user: "{{ server.username }}"
    idrac_port: "{{ target_idrac_port }}"
    idrac_password: "{{ server.temp_passwd }}"
    validate_certs: "{{ validate_certs }}"