# - name: "Check the current power state of the server"
#   ansible.builtin.uri:
#     url: "https://{{ server.permanent_ip }}/redfish/v1/Systems/System.Embedded.1"
#     user: "{{ server.username }}"
#     password: "{{ idrac_root_passwd }}"
#     validate_certs: "{{ validate_certs }}"
#     method: "GET"
#     use_proxy: yes
#     force_basic_auth: yes
#     return_content: yes
#   register: server_status

# - name: "Power off the server (Skipped if already OFF) before upgrade BIOS firmware"
#   dellemc.openmanage.redfish_powerstate:
#     baseuri: "{{ server.permanent_ip }}:{{ target_idrac_port }}"
#     username: "{{ server.username }}"
#     password: "{{ idrac_root_passwd }}"
#     validate_certs: "{{ validate_certs }}"
#     reset_type: "ForceOff"
#   when: server_status.json.PowerState == 'On'

# - name: "Upload the BIOS firmware from local path"
#   dellemc.openmanage.redfish_firmware:
#     baseuri: "{{ server.permanent_ip }}:{{ target_idrac_port }}"
#     username: "{{ server.username }}"
#     password: "{{ idrac_root_passwd }}"
#     validate_certs: "{{ validate_certs }}"
#     image_uri: "{{ bios_firmware }}"
#     job_wait: false
#   register: bios_upgrade_result

# - name: "Track BIOS upload job to completion"
#   uri:
#     url: "https://{{ server.permanent_ip }}/redfish/v1/TaskService/Tasks/{{ bios_upgrade_result.task.id }}"
#     user: "{{ server.username }}" 
#     password: "{{ idrac_root_passwd }}"
#     validate_certs: "{{ validate_certs }}"

#     method: "GET"
#     use_proxy: yes
#     status_code: 200, 202
#     return_content: yes
#     force_basic_auth: yes
#     headers:
#       Content-Type: "application/json"
#       Accept: "application/json"
#   register: bios_job_result
#   until: bios_job_result.json.TaskState == 'Starting'
#   retries: "{{ retries_count }}"
#   delay: "{{ polling_interval }}"

# - name: "Power on the server for upgrade BIOS firmware"
#   dellemc.openmanage.redfish_powerstate:
#     baseuri: "{{ server.permanent_ip }}:{{ target_idrac_port }}"
#     username: "{{ server.username }}"
#     password: "{{ idrac_root_passwd }}"
#     validate_certs: "{{ validate_certs }}"
#     reset_type: "On"
#   when: bios_job_result.json.Messages.0.Message == 'Task successfully scheduled.'
#   # when: bios_job_result.json.TaskState == 'Starting' and bios_job_result.json.Messages.0.Message == 'Task successfully scheduled.'


# - name: "Wait 10 mins for BIOS firmware to be applied"
#   wait_for:
#     timeout: 600
#   when: bios_job_result.json.Messages.0.Message == 'Task successfully scheduled.'

# - name: "Track BIOS firmware update job to be completed"
#   uri:
#     url: "https://{{ server.permanent_ip }}/redfish/v1/TaskService/Tasks/{{ bios_upgrade_result.task.id }}"
#     user: "{{ server.username }}" 
#     password: "{{ idrac_root_passwd }}"
#     validate_certs: "{{ validate_certs }}"

#     method: "GET"
#     use_proxy: yes
#     status_code: 200, 202
#     return_content: yes
#     force_basic_auth: yes
#     headers:
#       Content-Type: "application/json"
#       Accept: "application/json"
#   register: bios_final_result
#   until: bios_final_result.json.TaskState == 'Completed'
#   retries: 100
#   delay: 10

- name: "Update the iDRAC firmware from a single executable file available in a local path"
  dellemc.openmanage.redfish_firmware:
    baseuri: "{{ server.permanent_ip }}:{{ target_idrac_port }}"
    username: "{{ server.username }}"
    password: "{{ idrac_root_passwd }}"
    validate_certs: "{{ validate_certs }}"
    timeout: 90
    image_uri: "{{ idrac_firmware }}"
    job_wait: true
    job_wait_timeout: 600
  register: idrac_upgrade_result

- name: Wait 5 minutes for rebooting iDRAC after new firmware to be applied 
  ansible.builtin.wait_for:
    host: "{{ server.permanent_ip }}"
    port: 443
    timeout: "{{ idrac_wait_timeout | default(300) }}"
  register: waiting_idrac_up